url: http://localhost:4000
name: stevenja.co/bs/
markdown: kramdown
highlighter: pygments
exclude: [node_modules, Gruntfile.js, tmp]

email: stjacobs+blog@fastmail.fm

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

sass:
  sass_dir: _sass
